# ==============================================================================
# CẤU HÌNH GỬI MAIL XÁC THỰC OTP QUA SMTP.GMAIL.COM (CÂU 2 - MSSV: 24110028)
# ==============================================================================
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true


mail.from=lenguyenminhkhoi2006bl@gmail.com

mail.app.key=mvoa zjxt yutn pxsg
